#!/bin/bash
# Hot-function profiler for the DOS render loop, Bochs + gprof edition.
#
# Runs the drawing stress-test cart (tools/bench/app.heavy.lua.bak) under a
# gprof-instrumented i486 build inside Bochs, then symbolizes the gmon.out it
# produces. Output is a gprof flat profile = the hot functions of the render
# loop, ranked by self time. Deterministic, like tools/bench_bochs.sh.
#
# Pipeline (Bochs can't mount a host dir, so the engine is baked into an image):
#   1. bin/dos486prof/nibble8.exe  -- built with PG=1 (-pg, no LTO). See Makefile.dos.
#   2. clone FreeDOS image, inject C:\NIBBLE\ + the heavy cart + an FDAUTO.BAT
#      that runs --bench then FDAPM POWEROFF.
#   3. on clean exit DJGPP flushes C:\NIBBLE\gmon.out; pull it out with mtools.
#   4. i586-pc-msdosdjgpp-gprof <exe> gmon.out  ->  flat profile.
#
# Usage: bash tools/profile_bochs.sh [frames] [ips]
#   frames  uncapped frames to render  (default 60; -pg + heavy cart is slow)
set -e
cd "$(dirname "$0")/.."

FRAMES="${1:-60}"
IPS="${2:-16000000}"

BOCHS="${BOCHS:-/c/Program Files/Bochs-3.0/bochs.exe}"
BOCHS_DIR="$(cygpath -m "$(dirname "$BOCHS")" 2>/dev/null || dirname "$BOCHS")"
MTOOLS_DIR="${MTOOLS_DIR:-/c/msys64/mingw64/bin}"
DJGPP_ROOT="${DJGPP_ROOT:-/c/djgpp}"
GPROF="$DJGPP_ROOT/bin/i586-pc-msdosdjgpp-gprof.exe"
export PATH="$MTOOLS_DIR:$PATH"
export MTOOLS_SKIP_CHECK=1

B=tools/bench
BASE="$B/FD13LITE.img"
IMG="$B/fd-prof.img"
PART="$IMG@@32256"
BUILD=bin/dos486prof
CART_SRC="$B/app.heavy.lua.bak"
GENCONF=config/.bochsrc.prof.gen
WINROOT="$(pwd -W)"
GMON_HOST="$B/gmon.out"
LOG_HOST="$B/nibble8.prof.log"
REPORT="$B/gprof.flat.txt"

# --- preflight ---------------------------------------------------------------
[ -f "$BOCHS" ]             || { echo "ERROR: Bochs not found at $BOCHS." >&2; exit 1; }
[ -x "$GPROF" ]             || { echo "ERROR: gprof not found at $GPROF." >&2; exit 1; }
[ -f "$BUILD/nibble8.exe" ] || { echo "ERROR: $BUILD/nibble8.exe not found. Build the profiling target:" >&2
    echo "  mingw32-make -f config/Makefile.dos CC=i586-pc-msdosdjgpp-gcc DJGPP_PATH=$DJGPP_ROOT/ MARCH=i486 PG=1 OBJDIR=obj/dos486prof BUILDDIR=bin/dos486prof" >&2; exit 1; }
[ -f "$BASE" ]              || { echo "ERROR: $BASE not found (FreeDOS base image)." >&2; exit 1; }
[ -f "$CART_SRC" ]          || { echo "ERROR: heavy cart $CART_SRC not found." >&2; exit 1; }

# --- (re)build the profiling image when the engine is newer ------------------
if [ ! -f "$IMG" ] || [ "$BUILD/nibble8.exe" -nt "$IMG" ]; then
    echo "Preparing profiling image from $BASE ..."
    cp -f "$BASE" "$IMG"
    mmd   -i "$PART" ::/NIBBLE ::/NIBBLE/drive_c
    mcopy -i "$PART" -o "$BUILD/nibble8.exe" "$BUILD/CWSDPMI.EXE" "$BUILD/config.ini" "$BUILD/rom.zip" ::/NIBBLE/
fi

# --- pack the heavy cart -----------------------------------------------------
TMP="$(mktemp -d)"; cp "$CART_SRC" "$TMP/app.lua"
rm -f "$B/bench.n8"; ( cd "$TMP" && zip -q -X "$OLDPWD/$B/bench.n8" app.lua ); rm -rf "$TMP"
mcopy -i "$PART" -o "$B/bench.n8" ::/NIBBLE/drive_c/

# --- autoexec: run bench, then power off -------------------------------------
printf '@echo off\r\nSET DOSDIR=\\FREEDOS\r\nSET PATH=%%DOSDIR%%\\BIN\r\nC:\r\nCD \\NIBBLE\r\nnibble8.exe --cart bench --bench --bench-frames %s --debug\r\n\\FREEDOS\\BIN\\FDAPM.COM POWEROFF\r\n' "$FRAMES" > "$B/FDAUTO.BAT"
mcopy -i "$PART" -o "$B/FDAUTO.BAT" ::/FDAUTO.BAT
mdel  -i "$PART" ::/NIBBLE/gmon.out ::/NIBBLE/NIBBLE8.LOG 2>/dev/null || true

# --- generate bochsrc --------------------------------------------------------
cat > "$GENCONF" <<EOF
# Auto-generated by tools/profile_bochs.sh — do not edit by hand.
romimage:    file="$BOCHS_DIR/BIOS-bochs-latest"
vgaromimage: file="$BOCHS_DIR/VGABIOS-lgpl-latest.bin"
cpu:    model=i486dx4, ips=$IPS, reset_on_triple_fault=1
clock:  sync=none, time0=0
megs:   16
ata0:        enabled=1, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
ata0-master: type=disk, path="$WINROOT/$IMG", mode=flat, cylinders=65, heads=16, spt=63
boot:   disk
display_library: nogui
log:    $WINROOT/$B/bochs.prof.log
panic:  action=report
error:  action=report
info:   action=ignore
debug:  action=ignore
EOF

# --- run ---------------------------------------------------------------------
DEADLINE="${BENCH_TIMEOUT:-600}"
taskkill //F //IM bochs.exe >/dev/null 2>&1 || true
rm -f "$IMG.lock"
echo "Running Bochs (profiling): frames=$FRAMES ips=$IPS heavy cart ..."
"$BOCHS" -q -f "$GENCONF" >/dev/null 2>&1 &
BPID=$!
t=0
while kill -0 "$BPID" 2>/dev/null; do
    sleep 1; t=$((t + 1))
    [ "$t" -ge "$DEADLINE" ] && { echo "WARN: Bochs exceeded ${DEADLINE}s — killing." >&2; break; }
done
taskkill //F //IM bochs.exe >/dev/null 2>&1 || true
wait "$BPID" 2>/dev/null || true
rm -f "$IMG.lock"

# --- extract gmon.out + log --------------------------------------------------
rm -f "$GMON_HOST" "$LOG_HOST"
mcopy -i "$PART" -n ::/NIBBLE/gmon.out "$GMON_HOST" 2>/dev/null || true
mcopy -i "$PART" -n ::/NIBBLE/NIBBLE8.LOG "$LOG_HOST" 2>/dev/null || true
grep 'BENCH: loop done' "$LOG_HOST" 2>/dev/null | tail -1 || true
[ -s "$GMON_HOST" ] || { echo "ERROR: no gmon.out produced — the run failed or did not exit cleanly." >&2; exit 1; }

# --- symbolize ---------------------------------------------------------------
echo "=== gprof flat profile (top self-time functions) -> $REPORT ==="
"$GPROF" -b -p "$BUILD/nibble8.exe" "$GMON_HOST" > "$REPORT" 2>/dev/null
"$GPROF" -b -q "$BUILD/nibble8.exe" "$GMON_HOST" > "$B/gprof.callgraph.txt" 2>/dev/null || true
sed -n '1,25p' "$REPORT"
